

export const DECK = {
    "pt-br": [
        {"title": "Construção da Grande Pirâmide de Gizé", "summary": "Pirâmide monumental construída para o faraó Quéops", "year": "-2560"},
        {"title": "Código de Hamurábi Proclamado", "summary": "Um dos primeiros códigos de leis escritos", "year": "-1754"},
        {"title": "Fundação de Roma", "summary": "Estabelecimento lendário da cidade romana", "year": "-753"},
        {"title": "Nascimento da Democracia em Atenas", "summary": "Desenvolvimento da governança direta pelos cidadãos", "year": "-508"},
        {"title": "Batalha de Maratona", "summary": "Forças gregas repelem invasão persa", "year": "-490"},
        {"title": "Execução de Sócrates", "summary": "Filósofo ateniense condenado à morte", "year": "-399"},
        {"title": "Coroação de Alexandre, o Grande", "summary": "Rei macedônio inicia vastas conquistas", "year": "-336"},
        {"title": "Dinastia Qin Unifica a China", "summary": "Primeira unificação imperial da China", "year": "-221"},
        {"title": "Assassinato de Júlio César", "summary": "Ditador romano morto por senadores", "year": "-44"},
        {"title": "Nascimento de Jesus de Nazaré", "summary": "Início da figura central do Cristianismo", "year": "0"},
        {"title": "Erupção do Monte Vesúvio", "summary": "Destruição de Pompeia e Herculano", "year": "79"},
        {"title": "Édito de Milão Publicado", "summary": "Legalização do Cristianismo no Império Romano", "year": "313"},
        {"title": "Queda do Império Romano do Ocidente", "summary": "Deposição do último imperador romano do Ocidente", "year": "476"},
        {"title": "Hégira para Medina", "summary": "Migração de Maomé que marca o início do calendário islâmico", "year": "622"},
        {"title": "Coroação de Carlos Magno", "summary": "Retomada do título imperial no Ocidente europeu", "year": "800"},
        {"title": "Batalha de Hastings", "summary": "Conquista normanda da Inglaterra", "year": "1066"},
        {"title": "Assinatura da Magna Carta", "summary": "Rei inglês aceita limites ao poder real", "year": "1215"},
        {"title": "Saque Mongol de Bagdá", "summary": "Fim da era dourada do Califado Abássida", "year": "1258"},
        {"title": "Peste Negra na Europa", "summary": "Pandemia devastadora transforma a sociedade", "year": "1347"},
        {"title": "Queda de Constantinopla", "summary": "Conquista otomana encerra o Império Bizantino", "year": "1453"},
        {"title": "Colombo Chega às Américas", "summary": "Contato europeu com o Novo Mundo", "year": "1492"},
        {"title": "Início da Reforma Protestante", "summary": "Lutero desafia a autoridade da Igreja Católica", "year": "1517"},
        {"title": "Conquista Espanhola dos Astecas", "summary": "Cortés derruba o Império Asteca", "year": "1521"},
        {"title": "Derrota da Armada Espanhola", "summary": "Inglaterra repele grande invasão naval", "year": "1588"},
        {"title": "Publicação dos Principia de Newton", "summary": "Fundamentos da física clássica estabelecidos", "year": "1687"},
        {"title": "Revolução Gloriosa na Inglaterra", "summary": "Parlamento afirma supremacia sobre a monarquia", "year": "1688"},
        {"title": "Declaração de Independência dos Estados Unidos", "summary": "Colônias proclamam separação da Grã-Bretanha", "year": "1776"},
        {"title": "Início da Revolução Francesa", "summary": "Levante popular transforma o Estado francês", "year": "1789"},
        {"title": "Sucesso da Revolução Haitiana", "summary": "Primeira república negra estabelecida", "year": "1804"},
        {"title": "Batalha de Waterloo", "summary": "Napoleão é derrotado decisivamente", "year": "1815"},
        {"title": "Primeira Ferrovia Pública Inaugurada", "summary": "Início do transporte ferroviário moderno", "year": "1825"}
    ],
    "en": [
        {"title": "Construction of the Great Pyramid of Giza", "summary": "Monumental pyramid built for Pharaoh Khufu","year": "-2560"},
        {"title": "Code of Hammurabi Proclaimed", "summary": "One of the earliest written law codes","year": "-1754"},
        {"title": "Founding of Rome", "summary": "Legendary establishment of the Roman city","year": "-753"},
        {"title": "Birth of Democracy in Athens", "summary": "Development of direct citizen governance","year": "-508"},
        {"title": "Battle of Marathon", "summary": "Greek forces repel Persian invasion","year": "-490"},
        {"title": "Execution of Socrates", "summary": "Athenian philosopher sentenced to death","year": "-399"},
        {"title": "Coronation of Alexander the Great", "summary": "Macedonian king begins vast conquests","year": "-336"},
        {"title": "Qin Dynasty Unifies China", "summary": "First imperial unification of China","year": "-221"},
        {"title": "Assassination of Julius Caesar", "summary": "Roman dictator killed by senators","year": "-44"},
        {"title": "Birth of Jesus of Nazareth", "summary": "Beginning of Christianity’s central figure","year": "0"},
        {"title": "Eruption of Mount Vesuvius", "summary": "Destruction of Pompeii and Herculaneum","year": "79"},
        {"title": "Edict of Milan Issued", "summary": "Legalization of Christianity in the Roman Empire","year": "313"},
        {"title": "Fall of the Western Roman Empire", "summary": "Deposition of the last Western emperor","year": "476"},
        {"title": "Hijra to Medina", "summary": "Muhammad’s migration marking start of Islamic calendar","year": "622"},
        {"title": "Coronation of Charlemagne", "summary": "Revival of Western imperial title in Europe","year": "800"},
        {"title": "Battle of Hastings", "summary": "Norman conquest of England","year": "1066"},
        {"title": "Signing of the Magna Carta", "summary": "English king accepts limits on royal power","year": "1215"},
        {"title": "Mongols Sack Baghdad", "summary": "End of the Abbasid Caliphate’s golden age","year": "1258"},
        {"title": "Black Death in Europe", "summary": "Devastating pandemic reshapes society","year": "1347"},
        {"title": "Fall of Constantinople", "summary": "Ottoman conquest ends Byzantine Empire","year": "1453"},
        {"title": "Columbus Reaches the Americas", "summary": "European contact with the New World","year": "1492"},
        {"title": "Protestant Reformation Begins", "summary": "Luther challenges Catholic Church authority","year": "1517"},
        {"title": "Spanish Conquest of the Aztecs", "summary": "Cortés topples the Aztec Empire","year": "1521"},
        {"title": "Defeat of the Spanish Armada", "summary": "England repels major naval invasion","year": "1588"},
        {"title": "Publication of Newton’s Principia", "summary": "Foundations of classical physics established","year": "1687"},
        {"title": "Glorious Revolution in England", "summary": "Parliament asserts supremacy over monarchy","year": "1688"},
        {"title": "American Declaration of Independence", "summary": "Colonies proclaim separation from Britain","year": "1776"},
        {"title": "French Revolution Begins", "summary": "Popular uprising transforms French state","year": "1789"},
        {"title": "Haitian Revolution Success", "summary": "First Black republic established","year": "1804"},
        {"title": "Battle of Waterloo", "summary": "Napoleon decisively defeated","year": "1815"},
        {"title": "First Public Railway Opens", "summary": "Modern rail transport begins","year": "1825"},
        {"title": "Publication of The Communist Manifesto", "summary": "Marx and Engels outline revolutionary theory","year": "1848"},
        {"title": "American Civil War Begins", "summary": "Conflict erupts over union and slavery","year": "1861"},
        {"title": "Emancipation Proclamation Issued", "summary": "Slaves declared free in rebelling states","year": "1863"},
        {"title": "Meiji Restoration", "summary": "Japan modernizes under imperial rule","year": "1868"},
        {"title": "Unification of Germany", "summary": "Proclamation of the German Empire","year": "1871"},
        {"title": "Telephone Patented by Alexander Graham Bell", "summary": "Revolution in long-distance communication","year": "1876"},
        {"title": "Berlin Conference Concludes", "summary": "European powers divide Africa","year": "1885"},
        {"title": "Wright Brothers’ First Flight", "summary": "Powered airplane achieves sustained flight","year": "1903"},
        {"title": "Russian Revolution", "summary": "Tsarist regime overthrown by Bolsheviks","year": "1917"},
        {"title": "End of World War I", "summary": "Armistice halts global conflict","year": "1918"},
        {"title": "Discovery of Penicillin", "summary": "First true antibiotic identified","year": "1928"},
        {"title": "Stock Market Crash of 1929", "summary": "Global economic depression triggered","year": "1929"},
        {"title": "Adolf Hitler Becomes Chancellor", "summary": "Nazi regime rises in Germany","year": "1933"},
        {"title": "Start of World War II", "summary": "Germany invades Poland","year": "1939"},
        {"title": "Attack on Pearl Harbor", "summary": "United States enters World War II","year": "1941"},
        {"title": "D-Day Landings", "summary": "Allied invasion of Normandy","year": "1944"},
        {"title": "Atomic Bombing of Hiroshima", "summary": "First wartime use of nuclear weapon","year": "1945"},
        {"title": "Founding of the United Nations", "summary": "International body created to maintain peace","year": "1945"},
        {"title": "Indian Independence Achieved", "summary": "British rule ends in India","year": "1947"},
        {"title": "People’s Republic of China Proclaimed", "summary": "Communist state established under Mao","year": "1949"},
        {"title": "Discovery of DNA Double Helix", "summary": "Structure of genetic material revealed","year": "1953"},
        {"title": "Brown v. Board of Education Decision", "summary": "U.S. Supreme Court outlaws school segregation","year": "1954"},
        {"title": "Launch of Sputnik 1", "summary": "First artificial satellite in orbit","year": "1957"},
        {"title": "Cuban Revolution Triumphs", "summary": "Fidel Castro takes power","year": "1959"},
        {"title": "Construction of the Berlin Wall Begins", "summary": "Physical division of East and West Berlin","year": "1961"},
        {"title": "Cuban Missile Crisis", "summary": "Nuclear standoff between U.S. and USSR","year": "1962"},
        {"title": "Assassination of John F. Kennedy", "summary": "U.S. president killed in Dallas","year": "1963"},
        {"title": "Moon Landing by Apollo 11", "summary": "First humans walk on the Moon","year": "1969"},
        {"title": "Fall of Saigon", "summary": "Vietnam War ends with communist victory","year": "1975"},
        {"title": "Iranian Revolution", "summary": "Islamic Republic replaces monarchy","year": "1979"},
        {"title": "Fall of the Berlin Wall", "summary": "Symbolic end of Cold War division","year": "1989"},
        {"title": "Dissolution of the Soviet Union", "summary": "USSR formally ceases to exist","year": "1991"},
        {"title": "End of Apartheid in South Africa", "summary": "First multiracial elections held","year": "1994"},
        {"title": "Creation of the World Wide Web", "summary": "Public release of web technology","year": "1991"},
        {"title": "September 11 Attacks", "summary": "Terrorist attacks reshape global politics","year": "2001"},
        {"title": "Human Genome Project Completed", "summary": "Full mapping of human DNA finalized","year": "2003"},
        {"title": "Global Financial Crisis", "summary": "Worldwide economic downturn triggered","year": "2008"},
        {"title": "Arab Spring Begins", "summary": "Widespread uprisings across Middle East","year": "2010"},
        {"title": "Discovery of Higgs Boson", "summary": "Particle confirming mass mechanism observed","year": "2012"},
        {"title": "Paris Climate Agreement Signed", "summary": "Global pact to address climate change","year": "2015"},
        {"title": "Brexit Referendum Passed", "summary": "United Kingdom votes to leave EU","year": "2016"},
        {"title": "COVID-19 Declared Pandemic", "summary": "Global health emergency announced","year": "2020"},
        {"title": "James Webb Space Telescope Launched", "summary": "Advanced space observatory sent into orbit","year": "2021"},
        {"title": "Russia Invades Ukraine", "summary": "Full-scale war erupts in Eastern Europe","year": "2022"},
        {"title": "First Image of a Black Hole Captured", "summary": "Event horizon directly photographed","year": "2019"},
        {"title": "Gutenberg Prints the Bible", "summary": "Movable type revolutionizes publishing","year": "1455"},
        {"title": "Council of Nicaea Convenes", "summary": "Foundational Christian doctrines formalized","year": "325"},
        {"title": "Norman Conquest of Sicily", "summary": "Birth of multicultural Mediterranean kingdom","year": "1061"},
        {"title": "Signing of the Treaty of Tordesillas", "summary": "Spain and Portugal divide new lands","year": "1494"},
        {"title": "Trial of Galileo", "summary": "Scientist condemned for heliocentrism","year": "1633"},
        {"title": "Boston Tea Party", "summary": "Colonial protest against British taxation","year": "1773"},
        {"title": "Louisiana Purchase Completed", "summary": "United States doubles its territory","year": "1803"},
        {"title": "First Opium War Begins", "summary": "Conflict opens China to Western trade","year": "1839"},
        {"title": "Seneca Falls Convention", "summary": "First women’s rights convention in U.S.","year": "1848"},
        {"title": "Suez Canal Opens", "summary": "Major maritime shortcut inaugurated","year": "1869"},
        {"title": "Assassination of Archduke Franz Ferdinand", "summary": "Trigger for World War I","year": "1914"},
        {"title": "Discovery of King Tutankhamun’s Tomb", "summary": "Intact Egyptian royal burial found","year": "1922"},
        {"title": "Spanish Civil War Begins", "summary": "Prelude to wider European conflict","year": "1936"},
        {"title": "Formation of NATO", "summary": "Western military alliance established","year": "1949"},
        {"title": "Korean War Outbreak", "summary": "Conflict divides Korean Peninsula","year": "1950"},
        {"title": "Algerian War of Independence Begins", "summary": "Colonial rule challenged in North Africa","year": "1954"},
        {"title": "European Union Formed", "summary": "Maastricht Treaty establishes political union","year": "1993"},
        {"title": "Rwandan Genocide", "summary": "Mass slaughter shocks the world","year": "1994"},
        {"title": "Launch of Facebook", "summary": "Social media platform goes live","year": "2004"},
        {"title": "First iPhone Released", "summary": "Smartphone revolutionized mobile technology","year": "2007"},
        {"title": "Arab–Israeli Six-Day War", "summary": "Israel captures significant territories","year": "1967"},
        {"title": "Nelson Mandela Released from Prison", "summary": "End of long imprisonment under apartheid","year": "1990"},
        {"title": "Discovery of Machu Picchu", "summary": "Inca citadel revealed to global audience","year": "1911"},
        {"title": "Battle of Gettysburg", "summary": "Turning point in American Civil War","year": "1863"},
        {"title": "Storming of the Bastille", "summary": "Symbolic start of French Revolution","year": "1789"},
        {"title": "Establishment of the Inca Empire", "summary": "Expansion of Andean civilization","year": "1438"},
        {"title": "Battle of Thermopylae", "summary": "Spartan stand against Persian army","year": "-480"},
        {"title": "Sack of Rome by Visigoths", "summary": "First major fall of the Eternal City","year": "410"},
        {"title": "Coronation of Queen Elizabeth II", "summary": "Beginning of longest British reign in modern era","year": "1953"},
        {"title": "Tiananmen Square Protests Suppressed", "summary": "Chinese government crushes demonstrations","year": "1989"},
        {"title": "Chernobyl Nuclear Disaster", "summary": "Catastrophic reactor explosion in Ukraine","year": "1986"},
        {"title": "Signing of the Kyoto Protocol", "summary": "International emissions reduction treaty","year": "1997"},
        {"title": "Discovery of America by Vikings", "summary": "Norse explorers reach North America","year": "1000"},
        {"title": "Battle of Agincourt", "summary": "English longbowmen defeat French army","year": "1415"},
        {"title": "Edict of Nantes Issued", "summary": "Religious tolerance granted to French Protestants","year": "1598"},
        {"title": "American Constitution Ratified", "summary": "Framework for U.S. government adopted","year": "1788"},
        {"title": "Gold Rush in California", "summary": "Mass migration in search of gold","year": "1848"},
        {"title": "Transcontinental Railroad Completed", "summary": "United States linked coast to coast","year": "1869"},
        {"title": "Assassination of Mahatma Gandhi", "summary": "Indian independence leader killed","year": "1948"},
        {"title": "Formation of the United Nations Declaration of Human Rights", "summary": "Global rights framework adopted","year": "1948"},
        {"title": "Apollo 13 Mission Crisis", "summary": "Astronauts safely return after in-space explosion","year": "1970"},
        {"title": "Watergate Scandal Resignation", "summary": "U.S. president resigns amid scandal","year": "1974"},
        {"title": "Fall of the Bastion of Apartheid Laws", "summary": "Legal racial segregation dismantled","year": "1991"},
        {"title": "Launch of Bitcoin Genesis Block", "summary": "First decentralized cryptocurrency created","year": "2009"},
        {"title": "Arab Oil Embargo Begins", "summary": "Energy crisis impacts Western economies","year": "1973"},
        {"title": "Establishment of the International Space Station", "summary": "Permanent human presence in orbit begins","year": "1998"},
        {"title": "Signing of the Good Friday Agreement", "summary": "Peace deal in Northern Ireland","year": "1998"},
        {"title": "Discovery of the Rosetta Stone", "summary": "Key to deciphering Egyptian hieroglyphs","year": "1799"},
        {"title": "Battle of Stalingrad", "summary": "Soviet victory turns tide against Nazis","year": "1943"},
        {"title": "Marshall Plan Announced", "summary": "U.S. aid rebuilds Western Europe","year": "1947"},
        {"title": "Partition of India", "summary": "Creation of India and Pakistan","year": "1947"},
        {"title": "First Female Prime Minister Elected", "summary": "Margaret Thatcher takes office","year": "1979"},
        {"title": "Nelson Mandela Elected President", "summary": "First Black president of South Africa","year": "1994"},
        {"title": "Assassination of Martin Luther King Jr.", "summary": "Civil rights leader murdered","year": "1968"},
        {"title": "Launch of YouTube", "summary": "Video-sharing platform introduced","year": "2005"},
        {"title": "Signing of the Treaty of Versailles", "summary": "Peace settlement ends World War I","year": "1919"},
        {"title": "Invention of the Printing Press", "summary": "Movable type accelerates knowledge spread","year": "1440"},
        {"title": "Battle of Yorktown", "summary": "British surrender in American Revolution","year": "1781"},
        {"title": "Opening of the Panama Canal", "summary": "Atlantic and Pacific connected","year": "1914"},
        {"title": "Establishment of the League of Nations", "summary": "First global peace organization formed","year": "1920"},
        {"title": "Discovery of X-rays", "summary": "New form of electromagnetic radiation identified","year": "1895"},
        {"title": "First Powered Television Broadcast", "summary": "Television enters public life","year": "1928"},
        {"title": "Launch of ChatGPT", "summary": "AI chatbot released to the public","year": "2022"},
        {"title": "Chicxulub Asteroid Impact", "summary": "Massive asteroid strike triggers dinosaur extinction","year": "-66000000"},
        {"title": "Cryogenian Snowball Earth", "summary": "Planet experiences near-total global glaciation","year": "-720000000"},
        {"title": "Ediacaran Biota Emerges", "summary": "First large complex multicellular life appears","year": "-600000000"},
        {"title": "End-Permian Mass Extinction", "summary": "Most severe extinction event in Earth history","year": "-252000000"},
        {"title": "Paleocene–Eocene Thermal Maximum", "summary": "Rapid global warming event disrupts ecosystems","year": "-56000000"},
        {"title": "Formation of the Himalayas", "summary": "Collision of India and Asia reshapes climate","year": "-50000000"},
        {"title": "Opening of the Drake Passage", "summary": "Ocean circulation shifts toward Antarctic glaciation","year": "-34000000"},
        {"title": "Antarctic Ice Sheet Formation", "summary": "Permanent ice sheet develops over Antarctica","year": "-34000000"},
        {"title": "Messinian Salinity Crisis", "summary": "Mediterranean Sea largely evaporates","year": "-5960000"},
        {"title": "Zanclean Flood Refills Mediterranean", "summary": "Atlantic waters refill the Mediterranean basin","year": "-5330000"},
        {"title": "Onset of Northern Hemisphere Glaciation", "summary": "Large ice sheets form in the Arctic","year": "-2600000"},
        {"title": "Toba Supereruption", "summary": "Massive volcanic eruption impacts global climate","year": "-74000"},
        {"title": "Younger Dryas Cooling Begins", "summary": "Abrupt return to near-glacial conditions","year": "-10900"},
        {"title": "Younger Dryas Ends", "summary": "Rapid warming resumes in Northern Hemisphere","year": "-9700"},
        {"title": "8.2 Kiloyear Climate Event", "summary": "Sharp global cooling episode","year": "-6200"},
        {"title": "Minoan Eruption of Thera", "summary": "Volcanic blast alters regional climate","year": "-1600"},
        {"title": "Late Antique Little Ice Age Begins", "summary": "Volcanic-driven cooling affects Eurasia","year": "536"},
        {"title": "Medieval Warm Period Peaks", "summary": "Relatively warm climate in North Atlantic","year": "1000"},
        {"title": "Little Ice Age Onset", "summary": "Centuries of cooler global temperatures begin","year": "1300"},
        {"title": "Huaynaputina Eruption", "summary": "Volcanic blast causes global crop failures","year": "1600"},
        {"title": "Laki Eruption in Iceland", "summary": "Volcanic gases trigger climatic anomalies","year": "1783"},
        {"title": "Tambora Eruption", "summary": "Leads to the Year Without a Summer","year": "1815"},
        {"title": "Year Without a Summer", "summary": "Global cooling devastates harvests","year": "1816"},
        {"title": "Krakatoa Eruption", "summary": "Explosive eruption affects global sunsets and climate","year": "1883"},
        {"title": "Dust Bowl Drought Begins", "summary": "Severe drought and dust storms in North America","year": "1930"},
        {"title": "Agung Eruption", "summary": "Volcanic aerosols cool global temperatures","year": "1963"},
        {"title": "Mount St. Helens Eruption", "summary": "Major volcanic eruption impacts regional climate","year": "1980"},
        {"title": "El Niño of 1997–1998", "summary": "Powerful warming event disrupts global weather","year": "1997"},
        {"title": "Mount Pinatubo Eruption", "summary": "Volcanic aerosols cause temporary global cooling","year": "1991"},
        {"title": "Indian Ocean Tsunami", "summary": "Massive earthquake triggers devastating tsunami","year": "2004"},
        {"title": "Hurricane Katrina", "summary": "Powerful storm reshapes U.S. Gulf Coast","year": "2005"},
        {"title": "European Heatwave", "summary": "Extreme temperatures cause widespread fatalities","year": "2003"},
        {"title": "Australian Black Summer Fires", "summary": "Record wildfires intensified by heat and drought","year": "2019"},
        {"title": "Arctic Sea Ice Minimum Recorded", "summary": "Lowest Arctic ice extent observed","year": "2012"},
        {"title": "Pacific Northwest Heat Dome", "summary": "Unprecedented heatwave breaks temperature records","year": "2021"},
        {"title": "Pakistan Megafloods", "summary": "Extreme monsoon flooding displaces millions","year": "2022"},
        {"title": "Atlantic Meridional Overturning Weakening Observed", "summary": "Key ocean current system shows signs of slowdown","year": "2023"},
    ]
}